### ISSUE TITLE
provide a license

### ISSUE THREAD

**Issue by georgringer** [DavidBruchmann/wdb-content-conditions#3]
please provide a license.txt as otherwise the code can't be used legally because it would be proprietary

**Comment by DavidBruchmann** [comment]
as the license is mentioned in composer.json I partially disagree.  But it's good being clear and I added the file with GPL 2.  
Thanks for reporting!

**Comment by georgringer** [comment]
See eg https://github.com/DavidBruchmann/wdb-content-conditions/blob/main/LICENSE.txt which supports better description for the end user, thx for adding

**Comment by DavidBruchmann** [comment]
Thanks to you!
I'm not sure if I'm supposed to adjust more, let me know if that's the case.

**Comment by georgringer** [comment]
No, everything is fine, thx a lot
